### ISSUE TITLE
Undefined symbol 

### ISSUE THREAD

**Issue by dwightkuo** [medvedevgroup/TwoPaCo#19]
/sc1/apps/pets/SibeliaZ/bin/twopaco: symbol lookup error: /sc1/apps/pets/SibeliaZ/bin/twopaco: undefined symbol: _ZN3tbb8internal24concurrent_queue_base_v818internal_push_moveEPKv

**Comment by iminkin** [comment]
Is TBB installed properly on your computer?

**Comment by dwightkuo** [comment]
I didn't see any issues during installation other than this issue:
Linking twopaco to TBB fails #13

It was fixed by following the suggestion in the issue
