### ISSUE TITLE
GFA version update

### ISSUE THREAD

**Issue by ChriKub** [medvedevgroup/TwoPaCo#3]
Is it planned to update the GFA output to the new GFA v2 or have an option to choose v2 as output?
I would like to use TwoPaCo with another tools that needs GFA v2 as input.

**Comment by ilyaminkin** [comment]
Yes, I will do that this week.

**Comment by ChriKub** [comment]
Thanks.

**Comment by ilyaminkin** [comment]
Hi again. Sorry for the delay, but now TwoPaCo supports GFA2. I couldn't verify it as Bandage seems to work with GFA1. Notice that the interface is slightly different now. Let me know if you have any issues with it.
