### ISSUE TITLE
error: Inconsistent read size

### ISSUE THREAD

**Issue by ChriKub** [medvedevgroup/TwoPaCo#5]
Hi,

When running TwoPaCo with any dataset that consists of at least two sequences of different size (in one, or more files) I almost immediately get this error message:

>Round 0, 0:1048576
>Pass    Filling Filtering
>1       error: Inconsistent read size

Is this wanted behavior, that TwoPaCo can only deal with input sequences of the same size?

Thanks,
Chris

**Comment by ilyaminkin** [comment]
Did you check out the master branch?

**Comment by ChriKub** [comment]
Yes

**Comment by ChriKub** [comment]
Solved by updating and new install.
