### ISSUE TITLE
Unable to create temp file

### ISSUE THREAD

**Issue by ChriKub** [medvedevgroup/TwoPaCo#7]
Hi,

in all my runs, independent of the provided location TwoPaCo is unable to create a temp file at the given location.

`twopaco --tmpdir /home/TwoPaCo/tmp/ --test -t 1 -k 11 -f 20 -o /home/TwoPaCo/test.dbg /home/TwoPaCo/examples/example.fa`

What am I doing wrong here?

Thanks,
Chris

**Comment by ilyaminkin** [comment]
Do you have permission to write in the temporary folder?

**Comment by ChriKub** [comment]
Yes. I have the permission to write in the /tmp folder of the file system as well as in the /home/TwoPaCo/tmp/ folder I created for TwoPaCo

**Comment by ilyaminkin** [comment]
Are you trying to use the master branch?

**Comment by ChriKub** [comment]
Yes

**Comment by ChriKub** [comment]
After an update it seems that it only happens when using  --test

**Comment by ilyaminkin** [comment]
Fixed in 0.9.2.
