### ISSUE TITLE
gfa1 Format issue (path orientation)

### ISSUE THREAD

**Issue by ChriKub** [medvedevgroup/TwoPaCo#8]
Hi,

the pats in the gfa1 dumped by graphdump seem to have a wrong format. For some of the segments in the path the the orientation is missing and for all segments that have one the orientation is given before the segment number instead of after (although I'm not sure if this is an actual error or if it is allowed based on the format specification)
Output:
`P       seq1_repeat_seq2_seq3   -23,17,-31,27,-8        31M,31M,31M,31M`
gfa spec example:
`P	14	11+,12-,13+	4M,5M`

Is this the correct format or is there something wrong?
Thanks,
Chris

**Comment by ilyaminkin** [comment]
That is probably a bug, I will make a minor release. Thanks for pointing that out.

**Comment by ilyaminkin** [comment]
Fixed in 0.9.2.
